version: '3'
services:
  my-standalone-postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  container-netflix-backend:
    image: image-docker-netflix-backend
    ports:
      - "8085:8085"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - my-standalone-postgres